apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCtdoibXiq3hEZSkcaI1c49MMEam3ab+1dD+5xi40mErCEbB8SvFSAQ4GHlBuFoGNUpKTpZNV6WIFEWgBseYenMt/a1hH73IpNAvyY44tWEVLi9aa/iU85g7ydstqz2FR2h+Z+90fZB8epn7h5JinFk7Pg8zyWug1Jsy9tbHK7t9rN4aUN/4wi0jRtYdx03p2sJFd68Gw66eFPZn8ANGc8pSPEsWv7qGrNqfW+pX1bAaGt3T4l+qdXbILO9ARBbF/3q/+xkXWFMGKDrcB/UPjMF08RaRc8Gb456owfEcGBI1D64ikt+ondWnQprNT2u9maNn9O82sCDd9CscXoUvrWpXdMOwODmuCz4OjHWbTPYB9YF0sURmeSug2p59x7QK+AGz2uZoDPsE1WmaVAPOqq0SSFVmHtzzriBqobcI5uV2bT6xdIxgexqnFnVl+AWEuBwX9XjSkhPe0XTpnWHl8gOQZlUtWvBTkrcMrzMXCBoGR81ImKJKWHi0OZTKqW2A5zx36J/Z9eng+ItRz6MNQGhyQyZesKnf8TFXrbeNuPcYWfNP7whhtRf04bC0iiYaXX9o8LWbl+8EPUAqtXrXFsGlqXBk1Hvjl4o2kfYFhHtJI+ACcqlmXw+ym0b3S4ASV0sivbI+GxBfDN2aFSrsLxq6uBQAo6ty0WgQdssMP8++++P+j6waY7/CrU35nfa5SRSwhb4JbqUna54iH7lOWzzbMWTLZO7VeL7mGHaNetAoXp56IswCQ==
    ARTIFACTORY_PASSWORD: AgCAw59dQwd6qwqh2p5Dxh4Ap9pdiA0tXuo0HrFP0lLryvtO0r8bIuP3y54T4MzdHxORKQ5Vdi/WOJ6Oh73RxllLsfTonzeWNVuoUwNelHhiaHVaTDEYrsyloFsdQjDx0ZSuJ1K6+tbgyN+hXYAM8ln3EghsQF7K1bFq05SJ1IFWS54x2rlA1gsOuKA7uJiVN7pZfehhZpj0MZKYX5TiQhYahWPjM8oO7nmSUA1g4fEiPAzqIqg0L38O+qAzEwnZ+DB3LIe5ZpNSl0cu1U+tyGxXAZgQ+WqVZKd6ATCM3M6FF5vtym7d5HQXGUXNPzcK1fgFT/18bJnzE4zMvJf/EkKET81rXd/SwMNOvcOSrUOPmadosKgm8+NgIDaBKH58W57882OD1ncbG7L69TL4lq6XH6jIouvqwu0CE+VA+p4VYE1oItNf5JwVOSqOXahnc+wlCMD2FpoMqK6qE4+f20LB/V9F+1ks08AC89YAndZRa/T2YrjazKdZ7S6Yqb7N9aUl8jS/MeQeS6lLKbnrtbvFpF7YSJX5pAGOYf4qBcICcQ0H9wwK6d9DrXZ2DnEQ9r0awCa/7Hn7HLv1/ezewahgyAhH8KRaSEbHicAJhkQ0jI2al+bFSnB8VNSW7c3T3iNZMfPr4irQ4482KLxJ8a604wRCS8K2bt7/XZ/7Ff+IRdZXbJavcDHdsPFuUucmWue7Qkp59FRTw029xJO5L5CWRCRjJA==
    ARTIFACTORY_URL: AgCnMgCsrWHA/fmrTBM9z565Sus/QbYA5axYqgK5sMypX2Y7HAEDwP59DxMlL+ikAhabfELXlsLAVeyjg64d5sFKXVPIIOObaSL0zD2tXx+rp70fdS7JgvfDraw1FMreoxf0o9lDukp3ZE3HxTA4nrSqDGi+sQ7kyTxSQT5Sr4dkvKR4y9MtCp17pfRt/UkVz28bhzSROvw1kPsGOlQ6ACDHPYrPch/hjM8zLsQCR28f8tJZrmOoNDJl9Fk1xQxfGtVkehwaL+LdmVyQS9G0ug6krgXTuq17DuLYjZC5HFWmOiNE4Pb6wA+MvTfiK+SAbsGLYQgzZ4u9DVNbsJjzTN1u+NRs3UL6rdlfkGY5TvXDMnVIDW0zingmxZUn5d3uyYgBxdQTh9dDPMGdWDXREe8ifEmJolZDG3K8KwA4/UlEkP4sU5xucCikvwzP25dmBbxYMKFBRWNTUmb+G02WUCXU9CgD31WcJr+wgOnW/MCXMpyP+9KEsE7xXvbKJe+dc3Xe3FsoPvyC17wxHYSyC74Shc9WkcJ1w3JmETUx3R2ru3eOvA2gc4dt+tLFM3x6wwKdPNZua2yHziv+SUSKn7ZlMRGT48RfY05tTc9hvkh4CFYbNfSE1mcsB1q/ttVJKyVR5jlpl9CbhjT8VuWsWzxSjoXU+mfTvRjt6VXUMxs4oNQwqjqcGP17zh6FilzvFwaFMPYrbznHuBnGbVvDazktS/o4S+OVDBogIEKHvWFS9OOZdUZLjLG9FA==
    ARTIFACTORY_USER: AgB4SKxod2v2LllkdVvNeiNN7MUymsAWZrzdchiN3yj8otUNa/Ss7m/MZRnYfh5QgsDE3gefR2x4iO2m+PFhikHQNgRJgmPZyWmh+RReHk1MtqMXz0o58FxDvl4pKSbND+H5nL/a3RHjYBOrkZ7DnamMHA19rn4HiLWRTFoB9gd/6SwGIR360n8moKlmLVcsbtL34UQMCmf5ag1k0DrdBC+j78Oguz57COm8wZmLxYh8NuvwA66dHtqkJs7g9Qt1lXN1jhRdvyRyl9b1mgOCVyTC8rqjv/lOGuiuC1OzS6PzZ7o17uuO/xDw3cx4wyU4QEDLgEx4bkmB9s/1BHLeqsprlGI8ieU5DzQm7r721lpaTlaXe/Vssu3kvg6bhgOnvNF9hfAov4Zv/0jdq80pbW57cOItGk0itxCNZPvWCtgYVTD185rtx0boqVHKzeDCNEr890Fll2IQjKwPwYDLXcln+eWlwEG0VsOLYCpqi2M+cT2mAuSrxN8oKOOY2pD6X7Sy8NDeJmaxVpdcdPxjApI5bO/TzT8ixxiwaLnbYxnGrozbCwd2Ra+uBWK0odayXZJBVcmwLk0W+c7eoUZg8JtZ1wNCB3KbBFL85EubLP9gKnR5M+rE0nZTtmOyT8kPIk1zBlQOXz/PxGy6BIFcVGzuMY+kSH1ag90g/GkCiJffcbp+2V2w/0kYtWbI68BQHCezCZTBPQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2022-01-14T02:34:15Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2022-01-14T02:35:39Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

