apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgArFJJG4lSTjes6LBtMHJeU8bhClbe9rEiZNLRyWZdoBWNwwR16Q2RDix9fu68UiZbWZNgV5OlPVnmKzansmIaQlZn1BTXkqKXhy5sfnBqZQW0a57TrL8eIwhs1IRJfiekuTPEpe5HYRBkHzqfMg7m9nRIrYNrDQbJJ3CN5rfT3SQY51r05JEuHwZviQAGgA8zpbDmpxCULyZPyp/L1iNk5i8EwgPQoZCBIZgEC9F8nu8ZRFSOc3hIncvSytk6dnTkkRlPaY63YcLBu0w9D6i3X2Ad08vhJmwxpVqsGybDj8TlNCEgq/vLGc2isXTNukKPlvA/ylL828FrMzXveaeujMqoUCQ7SgdV298Vdah7jCxMhfRUO7CxCtcQaFOj2jIv/qTQpbx9mvaKPLFFFBMujYkFJNnylCXyNui06cgarJjJPdcQIril9T56f5E5Ckj5Tw/CYGC2c8VgAz4rRzGWlVWHGtc+7X6HwuvnqcNJeDWyfja3dgKhndzzpMmia/qWdIt+HYj8suM1etiZ7sL74lSpTpweHIH+W62TifQMUmfXSLFJzM05dF9cge2mGi12+L6CllFWikoNU1SJHuBUb2cHLtZE2oIBUTX5DxEI8NbmEmPVFf2H0Y0quOSrX2Deci+c3eZ9tbuU9frN62o78LTP4kM2D/foCGUq/3/NlbEzHDSY/ngO8dI3qztyWH7Nd0sDHOw/zBnqmeiDMidkDNJljbu2RHOxA9M4ZOMwS+2gYr2WCSCuT
    username: AgBA7pP3RkoK9tZTSsudOCazTRPeR5T8cxor8tAYaThHfz4NjMOgSyFw3AAGNGRD0uQWCsIYE4a/ycXid8G4z9YQGaTx157gQX6qd2yZzHbYbNnAg/qUxJlCv7DL1S0V5YRAjKrfhJjBzU/dqKcDwuIWTtDkOlDDyoBuls8S3Pjk2z+Q/h5QeMdaynmFFhJecmmVOe+hECb2tL8s+aANa/5SDYGlyRziwuGYvun/rmnvgbjUQh6nQxjiTQEvxFnwuCRLX4E609AP//eGTz0VgZBoCjTGrdLIYZQeNlPRRlC7jJcCl37bHPqTkSoNUs94D8vKPG9m/ZM5gNeI5hbj+JNFTe/wtk7hTWiPiz5NSn2zXRr4pRU/z68Fr4dRKsllj0uxfevirUxj8A6wln8snKEGBxiPj/B5Ig1P6uSjuceZ+m1qDcaic7wDVw1f+a/U/m4oL6JZQyb7RwY0Zie25Xrxi71/Wc8ygBjp+obrdG5w4jAgWR0OK+DKCELwuam/WJZrUF9Pa6afqrjKhlRlcvYX4xeen/Z/f/Yow9lwhqYzB6+ccjjJj6ZYJkEJxPMcyJxLisyPKieO42r4D4HKcKtXnpt8VOsvj9E9F+Oxp6DHfTvaKri/zgHBy8l9bwcIgPY36B5d3Z2kfuKv6l2jvceR4d2aQ3OEW2j/gcNIiPbKGI4Yp1af9OjFaS/yFTDnhhtiCHgg3gololY=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

