apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgClfDCS5FhWlPtH8Z5y7MSgeYFtWxX/f7HldfcbBMSTDgLN94er2MX9/7b5VAD2fbYIrR2laOWGeObeG00HzkaIUnrWEIkmjC5yBe/qmINgsThYgl+78M4iXZMm+YuVClMj4fLkszH8ZzQHLR7XpkvSYjcjhLANn6LKUDnhdHykTjXItlDdjaWFLx5+04CjwTAgfEoRgnF6ZroEJ9ZgALpc9bLV5qSjzaDOX16oIGCP1uZY/qFeYvZOCHuk05EzEgX4/s+Vt6mqaFCxTNOP8gbjgCfb53nZvjMHtfMD+fLPnBf7uiO1858wqlcIMQuV4pB9vsxLXi7CJq3fuH/SjQ+AeSMiboh9AxgMt1zx7SJAmbROUXeiACjXJISyfkQe2w0HTvHjOqLhRCHIlGbDwuJ9780gUeEzEiKr35y3DCZFBhuVljHiBs+Uf9bEEooHLnQU8XpAYy0vS3luB+ZzP9tOGVoMADiGsy+UVer1QBcRUuVlxy5jzAOQ/9TQ7KzyYqHMZx1fQIIGyPux4N3k42YGo44aZiHWOoke9gTDG14MCAE+Zti6cjqGdr4OTlOKdR2yTQjNWI49a8sGHIJwhlaoIcn4I/4vZxYsl5Vlsxw/cJFsjPI3C2UnKDp47G8RqnSE7DdT4xz6B6blTviBVHWFIycgeDFNMn97QLV2EiUW533csROspMUNg27FPhbdKuSpyecAthcffUq5sslLLJOS7wCD56YT7CNDbN+VYKjYbUpiZ0z88g0s
    username: AgBFZQRQbsuzXhnpDnam21aZmDMgNeXpYwTC8qPmQRkTkkbcCaBvCkpattWOgfp/j0p1fKgH8xbGmGbYaZ16nLc67cg5OSXIu7jM5Si6LRWSIsiK77VBNgux2ox71n+7XCzT1crPttcVjCuJNYRe6cKETYcDh1+uSbBYfG5o4gzb6DtfpxmdnybTZizHfmVymoYCxbCKFrlfHxx11X8cG/6ThthO4/WGIJF+gTNClsG5NAonD1FCmaVYVQUBdAEla4upQizaDesPdvwfCcqmzMywImeEpBtu3NIhsX/Dt49teWrLBSKVrv/AoQzwfvsfd3jK32k27eMY+UU4klAAMg+54gDH1bSolMN7Qi85U9WslG+3CmpQoMD/9X6Gz3zDZY40wGqygQOsOi4miM8+AO2HW2IyT/wI4NjBF9L6Lt3ISSwUn5U355RXmGtXHP4EZKM1G4JmzdGW9PuEzufsIhEuMgn80lfWtWv0sVkeCELizb4FCLN+tOyhj0yXpEz5vKz+4CTqdaL3VB780bCOhnPBv7y1XgunbPItMFJOYZb+cgwhsODdy0i+T+lXjtWX8yosgop7jui8IYCSFUPUsZ7eb1l3kvUmolo2lPEsqzJKIq/Z/q4PFYQU4pom/RY50b7MXQ6DWZVDpcgxlYaSMSzh2d8gW3BtWy3HolE2cBYLfbV0KwNoVjCtrsdQGXYdfFMdLE45yAwwQos=
  template:
    data: null
    metadata:
      annotations:
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: kubernetes.io/basic-auth

