apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgBQqlFRsxn2zFgxNrHbWMGinlDanG7srLL0Lm/dXh7ZZ2evRhr9iRZJMEwO3w0/Ana2zhkXzrxIMVdsSpVSvsF9J/NdfO1WqyZzGBXtUfTMdqgvnJ4DCDDEueoCU1ZgOSslbyjI6zWa1bm/p602iZQFB72rwH33MrR+YVDh2aLf6xbRHS2gM6fPm0naOgNSi7j6WzT+2S10VeBB+v0RYvXoKXbwdYnU9kdB7IZa6NcueCd/m8H+KBfyWnmol+IEFavqhJaSxpqoFFMINS1yTGkPkJlAvFTGhDZwFEnv33DhdtrfhvDmDdj7rDHtu8gWlOJS2g4RgNclDFqVEdYYxEDhSADJn0JrZoZ7crvmkERIp4uJ4jGeuyO5fdYmthuK67/M50C0zLC9PZCRMBtbXb6VizQ7UXNex84au41Za+z7Z6S2gnbD9WbycNb+vzKVsGWDKFG/HZ5EogoNV7zk28Q+cDuU162/i5Z+OghsrgCWL8tAEgQQCzzx2djorUr2diQraqm//4AuuSaNDmJA1tXiAMQy4r8eK1L5cAwOku3FtKMwl8Rv/sGTA4BHwVR1A+KXlTKGo05MI3kpA+Vc3Ecc32Lce9YOFsKPgYPXcqqyLZdUXHJs9L1LFEidGTPArEedQ2H/3bkhE7FYdt/JezCdihCBCmyyHcpL5z8XcXWdxd45PZDNBfoL9QlexpJbg9/Ld1ztqFV/1aBGFtlECUycNloAVz1KHhl/wF20WmiTqe1c/KXzp1yvcKgRWU3eOVYjqCnKfJQ7WuIwJXEu5akfLtzY7K4W3sLeeUPwg0K17EwGNdx5tIO8IOl2CEqWFJJAcLKuGhKG5izxPHyy9yPhfXxi3VVZ4vydqRKQ4Nd6fESQ7lI2ovXW1wh21gZKtsrcukg54ii2VTpo3oSXFdPrrduPaVi2u6r6FS4XTnRRdVFCX3lpKj3fkyLfSHMLQGc=
    IBM_ENTITLED_REGISTRY_USER: AgAKiNARU7wCwpue3DqBRE+2wpfDObAlZTc6lgODBRpA+XLvXsBHuOa3T67ZYtGirD5OtUejsxPiltnpLsR1m2Esvtc5yvzMuu5jiEdg0sE5VnYgO3LX01Mz8OtHqEL0dJJfmHsjxir+xbG0TaEUgAO2ZtoOlD2vhtjR3uPkw/WTyiP/ktM2j8BvLkKjLjNzCELCLhMoWov2L9odvKVaDCiQ7kN9TCxtZM5gICPU8WRdqDKefpq3P5x55XnPAuqingku0G9ZVA8ji/RkcuMldPfSc771/2V3L206efoyjkRy87Z8qJs+ddecZMKRAERuh9kSYxo8QebPvsmTgC5Www0LrFR+Seoh9sxS2dIkB2oWiRXXc8XX8G279ggK3QrmWsEJuWWQ//rIgIIrTQSPEHjtNCs8q0FFbG0Zc9Tos8uPZbTPOuS/S123XoumO8on9psHbmGFsoDcP5X0RDh1+oja6D4GI3UeV5YKI1QnBac6k3jCzrXhU3zM/jVNL4+8dWD2tr4xUPBHwTKqjA5o6YCjIuSs6Ne8dEgt2Bduq4LB2CLecQifNAx/YiPEvcu7fTyOQiFFQvp7VY+lM6S9F+DKQAaPuMWBYQ9erELTFhym3KUh6ZHJ4r0+qlB+LkJ4p2MQGQfnuK7UG6QRnUrbTanwD7mfqW/8tiqlSVkOwp+2dXkAE7CrQaXmgllJmroUlQx46Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

