apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAASN0anLjUIpycSLElLzLuXMafBj3TEHh2/XVm3cq7thWzo7GFOFJXI7NpzFkNbT+kwF89R8aBkJK+3gOMOh+NBXhpoVQfuTV2DSSBgyPjaLs0l42iYTclzXrClBeaViwWf2iJZtnObMoiEGxHUvcP9/CqLM5j0Rd16h31E4di2M60UaI6sZ1M6YfyOC04QhnQ8tTcg26NOYR7/RDdR+yW69mCRt0v2dn5Yo3kxeVCNS/xQI7HrCrK69pDMmFkTTCpjVk2KFI9NU0jPNrJpJEWduu+vwApxVyE69mQmyjlHiMoISwguG0GlmvF5OE+J5sozrtlvYAFiRXkbIb8nQxzvaZqb0dzFB3Zr58taU63tWM9O2Q0nMo2LtBXx9JVfhsnEXK/ZlSCWgumrhx0zTKjyujsPjHTxtG8uKCTQmmWPfbdUH3zFPQJ1LWTwhR4+vgfHpnEoHVqObZL8zMUI04Ap8GSs4y1h3PfNdeRW+PT0yol5F/5hRWQhpYHPmQNxaRiPHzDFDOy50GrDzrgt+K7CFvjr+XChfliJZUVa6qq11NChpL0PP+nrmDon2o5Ds9SGQxcsKBk6xbmjCznQ7WAC58hVl+cUSzc3m/zf0MatzU4+XP4YBXzin5MaXCnohf6hkCLDygcz/IjRm8YQ73kLN6HDCBuoeGdG0yl1J25HgtifM9Dw6gd8b39xRxLCpguLv19Y6MqypsxBrh3mMbBCCANtB8IZwInDDGs/WOrtJLuSc2DDF/37J6NcjNPBAongnlZ3AVyMNoqIORAEcVfzk5MbbdJPbJeTr9LtjOhKK9Mu2rvtzk5GXnkhoNg6io1qxqVRb9qcsj6SQxrS1w2QKQqyE5F53Wh/F6d8fo4YUImuYXLIu+WqrJNlVT/TFl4kPy2G/mS5iQLYW15x6rdjtzOG/u6qW+e0wUAA3djEkVoH3Q2rT/fU7HtLH6SL8o=
    IBM_ENTITLED_REGISTRY_USER: AgBbo/6vvZQwBQt8tmQxwfAwrrAmzw2ekM4sq69GyusD+Q3UZj4Tlcgm+aqFgjo6InuXbN5n/ba8kKdhknP+VNpatzUFzMfvjbyzojXbRXw1JmA32cH/F12RyM0qapoZYT5A1v3jY7By2EK/JGIMIuvVz2u/yGfWnmsNIy6JGkvuJ/C3JwyHVEA3NdrdJCe5C9B7RNXiPEKKdErClXVHMwZbTlQnX1gMxJVyLHAMBqc8cTkwVcTmWJGL4XruxlYgPMLjxmMD4JO1czGICseIKMxg7QwZhLfUZogSYWZ5HeS+OchSb1psqfxpUhZMsVyLLR25OzBq7AKjlvcKg1rRmX8p7qJgUUAI5AJC7cCoWnEHwP+FXMp0dm0x1KR8vrhNVkN2EnfZGzy5r4EtW4Ca4kWMjXfOp9+6HZZiZT90WI1BBd8pw3GpCLnyUBKumEj8hxG09tSW6LJPyhSotj3rGnrB/+t6VCYG1AK9GuhyXyFcYvqMVg9PxAFoAtlw1M61kHgPd0Vag8ueWNc6EGYTjD6SCa4zBAuUSkaFtXdaN5DYVyk3mcDHRFkS66bjPUQaag90zfw4MNXIq2ZWdJL5AC56AeYJ4HudSb6d+DN1Xr1SBw/WAOs2d3NitapoM2dt3fb/XojwcKr78OFHZV0XdvTEknDTDTmHCX5z/MCSzVMXfldQGH2WiEakALvtbz/bOBagoQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

