apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-lauren-demo-rest-dev-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: lauren-demo/environments/dev
    repoURL: https://github.com/client-engineering-gitops-h/multi-tenancy-gitops-apps.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true