apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: mq-infra-dev
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/qm1-client-engineering-gitops-h' && body.repository.full_name == 'client-engineering-gitops-h/mq-infra'"
      bindings:
        - ref: cnkt-trigger-binding
      template:
        ref: mq-infra-dev
    - name: Lauren-demo-dev
      interceptors:
        - ref:
            name: "cel"
          params:
          - name: "filter"
            value: "header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/Lauren-demo-client-engineering-gitops-h' && body.repository.full_name == 'client-engineering-gitops-h/Lauren-demo'"
      bindings:
        - ref: cnkt-trigger-binding
      template:
        ref: Lauren-demo-dev
      