apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBB3lxw3wSfzUiJ5swO7eb/bACan32Mozwe6HR74j2xMyPJmtfc4hJ1hdUTAhVDNkyan7iF1E3MKRKsXWyNTa0Az5//pGoVGtfaPw9eB4iAwXLWR/bCs5BHzWHpymYZn7qfoHX3GmyNUpbyzmWjHtFGmnQ9YZC7v69WMa2OE6X6ZSqD86IGswDMwyvEaf/q7Ra2JUM2dTFKuX4+qWcIblppxxF5k5EcbeB6jUu8t9z44Q1BFlpRHTBJOyOsnAu5nQztr1GnK+0iW6/Qj77U3XGxFwqSrhojfY5Lmkwe5YyEKEsEimrIILwOOAJA/JTJam8sHgbLKB/GBCZggLnCVpx/HeKQxlhvlLBvAVKew9SlDQp+Z4jz4BXqoqM54wCTJz4dKQpwjSkyMW1jj527xu4/wnDZ+uJv0Kanpr8WEcflpGXoj5ioOxRW1L8gn+s7qUQ3kjfUNyZgUs73qM4w99IDEJgmQ9A/g+/7spOWOCf02o4FiLjVTqNQJEizvvMnKHgjt3YY9BqLj3ZqSprPsGpPB4aQK49SbOCSK4fI+wRg4w3BV+zUno6iipJCPlpDqsIFyXXPhbnYua/YxcdvtYkqsQosiaaGrTeQUAJIQ7FBd7kf2pv3GdWyKplZg/lf90rXCEqqc0jBI7Dr4NfZZ7zVhcebVxCXpAgmSblCb8UJSKoqtlwfesqiupfmWtotneMfZnQ1Xum4Ycl0fM2LLHIIJ/wNBZrS20pr9AgV0nhfz3jg087Slg==
    ARTIFACTORY_PASSWORD: AgARf5KKP7CVT3EFoLrA4F8HAW+zZV6V5vi/Ur3QD0kcCRQawL1tYsm2wLW8vonvVdLTfHrG9H3BajkabG8vUboo+Lx36YTbIiJBbf0z8Rvtntho3mJLLpxxmR2AJSA8eJc6z/jhffFbzsLK8AJIGzZYAyLxoQINF9mz6Yj0M2wYGEDW07F0VwUXv0HvvUmMLhn10RaxM/C7W67obNV9cA+98/jfnUHerMjZVYX4PS9Bu1pjyA74aGbdIu5C0zKPU1yaew/Jm5Yp7ZekxhK0TeC3dqrBh8F8HkH7oC3wb267ybztf7oXO+sLOPMtjx4NATsAgwfUHoM9lWkQG2jmAjtOr7cmmiL8CExT7regvWUyUxNur+CM7TVIppLkqlTVx6zMpnuH1I1xP7P+Cbxs0kEn7E5vehhj+ZQRWNOe+HHsVCzXDX11xylmTvGsKB0C2D3ANxxSTWBYozxgSE6CQGZ1yBCLbmkQaEa6fr56k2parDfn53zbdLbUrZ20IjeANAULixeAq4zs59Bmo9mhhy3lfgUXJeqF5QyHZJOoFzscYBv+ZJWrbAp6/ni+W5uHC41PCmwGLR+jZkNx7EAjor3NmbzSvvKQp4ICgAZgJzek7emNSi9UN0FYqOZPrC9147nOwbB9qVmnaEzh+aaH81IUMb50T9l720P4Wc7uMthh+D4/C2ndp+BXfJyo1bGd3XhQ44MH7kG3ZZzQAdtGNA/qx8GLfA==
    ARTIFACTORY_URL: AgCLzesdjeRJfuxlzusUUt6BLM3GQ1dcaPN6TMWr5AD/6MdKBYAiAl0Bt4gZzx2mnp9ocGXnRvv4b/63pgrtU7ACisoYBDYsBM3licbHheaF6tV3LwVwvS6MzlkgCy6GoYWFavXK+yUHCjM840JBPcKaNY++TmzWzuarjEaUBJJcocoos2zlRdi5HQtjYBB+AxYdbECPemDDuKj2ncDYJNNR+/Hv4MrBlyZWFSIDyzXnkZqIzPsltQpk5bvkeTKht7TjaCm9LZnbpJJ2yYpQAU22swqFdW+yl9Q4KA8NLGXDkJL2QiTRYLrh3/Z6efOuEIMAxi1SKsXz7JGo96OZBDoY95lse0Rtq7Bwx/Q7lenOqx2XUOD5JpDh5CJx9/CokgZe2SCBQwW3VjH2DFW0joCPni+Jyupj/Llo05ERSV0YF9HmBpZLF/lsvWwIQqnmJvq8GySQcZ3Z6TBi8r40RSgyrWBK1bSrUUGG6pJaNTIZ6xwQVkFxE1xjtjTQkmme/84n0VwiVjXp96wbLel2JF7dQxiFTLMsJhdWOwHuLiNnlJK7cbqS2Vqoihehs3LkOWnpNqIICItL6NHvhmuYtvrqWWQLnjDm7MYawqcwqIoDK+eB3vqF+Rl3A0vdoiQ8z0GRm/TgvFZMJibvZXSaMiQQ6iipfGh4/Vyxfcbi3evZJH7i0SQ0pQnUuNw9n3DdIc2lrPorQoUYhIWtiiAqLfQUBsbb1utzL8nh2kxerZ4Y0F6qKrAx1bb3bg==
    ARTIFACTORY_USER: AgBWgEUlptK/nPGBY+BLZOjT66Qzrj6iYM/+SIueh2zfHtSHyBwRupxkk24NpCtZjcWVNxn4S1IG9+0H20LtCui0D/gd1A11ME/qlEP4u3hlsPx/xlyoPBsLO/0U0ap8iMdfIFYQcAj191aZ/HooOA1P7K7WWoe3nGfs1pG9T9hjAoxaDineGrmZmskV7cZRGQH2d2y0p+ZxuJbmYd7EqqXzcqs+M3PUexisqAh7NQVrejfNquK844lT7N+3r0hJ+DHsiwZHWf4ZpUcy+p4VM1GdvXak/s4ngGLoqE77mmseUXFGX1CkVhtUa1HWlNbMC1H78y5vXsowBXyIfbdumpnLrrfJ2XcvSfGG+RdqFJlvRUoxtTQQ7hXYvf76owuLquiD9qQgKoCtBzNV8O2Dv1uc1Wf5bQ2MRG5vG0rDjPva+T5bDu6KM2xscZ5IdQJGVD7pyNwy2GPxRhH4mQXtHS4GtH/VFkCI/z18W2Vj8CX1vVHj2VmOJylcREuabftZzZ618ECA0/fIP5DS9SILr1YTEHF5gcHbfjQ5mgF8Ah2d1hltJrTgAsWQxqId/NQCxjg+m0s+rW/B24nIuxo1Toy9GRLIYFh+MvbXyGng1/xzS9GqYsuL6lE0JMksgtctMmenRy1XUePN7LjwugOhRc+g13XQhIG8KhBNEFEuLeS3vkiOiR5CN8/uqA5hMJ0lPE328Ew2Tg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-12-16T22:24:56Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-12-16T22:25:52Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

