apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAwHsgNM0PO9iceh0eRNEdtxq3EAmCtlVkIhESDrnO/9+oVTDqPlNiQ3RVn3luQDhBOjsqP628xqmuQdbaEevxJSlnJIkqK9B/uZHygdLhNLzd/fdIFqT8LZhqdoGK5NFgvsktRiMQEQu2w8HD0paqPlHIfW8OX2bfTJPJkhsBgzfXayXRMvh+DQyaKz015gHldxaMswVg+xo23kdp8pF/btLZRTI+mamRc0a2KS4IGSIMVIiSOQqjNjhw+v06NXzMh8/2teviJZk2yAuMyly6fYmx3NsQ94N+l+C1Mh9FCFaaYdsXCVT9Hofk5QBzohupv4UhEhCYNJFuRFP1tzOvwfs95COz95e9aqK5s0pgvmR9AMEEmQFJU+tNMO2qjh9dHrkUK5VmP9DJnfiGAvV/bIm/ElFlysZrDIFOrBvvWT+OgukMKWC9L+3pmBsVjfBISmVtIyopsCO7/dglqhAMUnDzDE0l+zV0JN7XGjwVpG9Gl/X1ZGlowK8SHJwMZj0JglSvwc7NHLmEMtk4mVuPJ9PtEpbSK+AlE2HR+4931zV9DqW6tTN4QYjB/akTXo1HyAjJ2fxkGBYd06yI52oR6aMOgl06vLV0WUr3Qb2TIbzEkeiFgHD6hTaOwoKHt+SIoIdH2Q+NEN6JG1+t8rG9Nvr8jvM4YrqKNnNKYaxEq7kyWIDrNVG+haNEP/a3ZHqzndvEQzU0H+KWkiqA21eOYhFQLGnI5D6WYP2IWItQ1FR/cyVtlwA==
    ARTIFACTORY_PASSWORD: AgBoNOTdODfu6taYcjwixgw41EnQ5WRxcgnDSHIaQgdYyWhUYVSahajV0Rl2zjVzTbtWC99Qc69zwaZgGyGi5aa1n6u7L4BRpONNpF1ZwmT8IbIj/cFz1mczOB7b2m7hAQvUImDFSUk6KfJGZt/MvZYRxUynyTdyiHTisH7vEfrQ+QxrL/bBLWjCtRRpYmqJoYgZqJisT4Gsl19G3w+A4j80C07j0lpzgNgeeEfsDKgGDNAdZwuHn0j5vc3ITTOcrCnNpVHVtJTAuEzo+AnH6TNBlXqOzdVRSLqosZGXosEDfh1whFke+jcNPwJlo0GsUnsHGZDNK/kyoj7kFKY4JyexZPBniwHUSRcCQsd9WKhAHk/wFfaqQTF+GpL+M/XFMqQFm3VwYlgQS1SVU1uOc99EtrP9HtocOq4VG6R//3NUs/WN5nKgtJFZvGWhx4sBRALUjC+Ux3zw+J7UalkF1W+7Feao4f39o2beaEbB2nn1rME7V6h46N2iu///k0hZH8YGay3lMVf2jW0OA6nSseUZT3zOXFe0F5fji6LYaZLyxzS7WQ8oM26Br56HUOLkE1kBwSanbfrgfMCvRFsA4saBVu3ykQ244vrdYWKcin8jD/11biRb/uVFTQpWfyMMtMl+4k922e6a0EMiNhgiCPw2ZiezNQ8XSQTaiQx75IK47kGZXnhc1ahMSATe99ngWvpr8L6fkj3VBAcnBTwkZa42Xk73BA==
    ARTIFACTORY_URL: AgAHdHKqMLSVns/GzWrplU5On+BRE90DxQQqT7jSwDMp/EFLdMcng6OaKfLP4IpQmmdP4lAxDtRp1mlXbg7elalSj78NtrXPupqcKneUbd+ku08X31X65z6TNv12RDCwJIoruIc7NCbuS01yi8Gxif7etNLq1lNzVe+ZBqXK7n9JQVggsa/f7xytU6YrXPbWQKKMJDP3a5U99zIph9b6QUNaQdvpFf3J981NGvNjglPY+SyyeGMJyGv0qMn3+SIbx3moAJcvpQ6NS4b1QcoMGZdOmGE37wggo+MQRFMyRyG0B1s0Q3IhfqAh4MJCAeTf0hrwQ2wD1aRk8IvK+NifXah60xU2WobaZXoFHnwrHPVDWFVDjpqzJYlDCxurj+P9G+WZrT85yX1oCx6BY7RmEP2YwefPu6GMVgY+wQlBv++BTLNdaIFxwk/PenFYRjDSGwqIDHnMsfIcR4ZFlc+bN9solpOtTGWQJCb/6wqF8npFS9tMLu0I481QzfBDaCkZ20LwfmpMP/tTgUqWO05x77KEvPQWK/PNoFdpEOjGf3ucp6bU8KAoQdEPs6u36UdCciRdHW2cqPkAS6kM5QVm2DsYVJxBSCtwEFu9V9R6e0TBIWfSYYuGMLbL1nStEm/aR46UAp79kjt8f5hlbaSLUXmTHHKV/ECMNFbyi31qtM3zVG0hL/J79URzbrRIogIg2mEK1NyyLovO2Jx9HHlgVS5ZES1UWZhX4FNcEfLh1SDhhToVskOT9nJ01w==
    ARTIFACTORY_USER: AgBFKqqt/wu+f/xk3/5rwpopgUVX2rcRvw2QWVg2u6FO+cA/rWlyIZ75XuFpniw3G4363n6177Qv3RS9S9unoyBHyqYAbCmxTbr14BYeJqzzyHiY3y1kUeaAerwWOFIVaVvlh9/LOfbe0uWMv6ReVqc15mRepMfnvW0YnrUD0WrikplF5FuKQ84eyF/dCqiSezu3+VbgUZ6j6jgTlbeNokNzerysO75d3sSA3IhGD8Q9/OZP5FFjlYQp5SBoybrkItbelr6kizA5F4Jaavq2o24iKNCXEewuVgZ4g7BP8alm81zZ7/XwD3T+cToIuPH2BY7Dj5xSdVs3CSL9xJbsKnea+/9Ho41Wigv5yYOXsBhMiugpIy2sa8VJpT4wogjvVcdr/LO7EbP2LWiePmmkI1kc09N8ZR0B8llGOtiJQ0YwMPJwP/a5GAh2/TCCqSFJctNqZ8sTbxtPhSVGTR8JQASAnumoM6iZAIPboMuUQ+2oy7dNmUFxhgkaSz68XXDDH7dMMxwramMoKQKzQlWVc4M5/oGjF9KdX8UcHwRA4cB0kepJGupMs+NN+YM6E6oy2khgKXxxuugKyQIsgjRWFx3VqRsB+m9Hdypd2jChAsG5j1qPCh2cw2fH1n5a9t6Xm0V820bZ7mwVEUMX+qylEMh+qgbubneT8iS4s2YeK47J9IFdkpkux8R1GGgKnvIQer/o/Tdp/g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:ownerReferences:
              .: {}
              k:{"uid":"19a4b29b-b5ed-4751-b5b2-c07fdf1615a0"}:
                .: {}
                f:apiVersion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:type: {}
        manager: controller
        operation: Update
        time: "2021-12-20T20:11:50Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

