apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAXm4wQGKjmNX9ruAwjQ7cpMPfHnIY/kyJbBigkWAfNSro958j1PaA5yym7SyDNYZuQqiWefU0Hay3X43KEDoVX3nnYUc1vMP2XhCRqwozkaYf4DrfR08M84SbZLJ9jLQ6Q2KUTDaOp+aAH1aqXkQk971orOmaXMf1DL+V0Mf7WwQCf5/kTeLdvuGUjq8Gg3jbU/R0ua5U+ArXWey77U/mUkoLpqqOn+P+zoAXfmjCeqRN0LA/U+gfY1EpZrUuS8WQi2kYyBWB3LMNSsg8n8GuRueBLmLkTLB9voO2fywSPR6p6Kf9U6hbAB1TRT6cBLLzk9AxqhFJgaJlBwcGXl028TMr/6MI6UatyHz7iQH8TpwnEmTF/RWkoKtJj0GzhNl9P1YrzloTBZmp7ZmQpVxYB9kBhj4buR8vXsGvg8zJfa8AkBxE8D2sEPzJkBqjc0sLwbOQUD01Fvu6aDqDstoSme2GBkbEF9sXhJz9ljJ9VH6FwHtSvs/yC2nFGxRYLOsilGZOYuuX9PcU8oT63c9Gw+rKZOjjxZn8EmqQ98mvbmGHIv6lUwA1/zxK224gAiApcGaiEOGEGBhRkI/gjkxzJQHCotIdHuMd+Vzv6G4OGwc42Ze1ZBaEtScaYTxvj/9hbovqyPfP3CBMyPBsKgktfQ+Omk0eyUWeWh3U0lk2b9ZyTfxYAudiy1131cFIjNfz2LhS2y+IBGhcJss+8qD0m6nR7JE2Giru/rh/MN8jkAdngCnUsCcgdxMt90O7IqXKupEKRCksSluyLx4ZbMWZ1dKQmCZ+QrN/NP6x6oiGQXZF+IxbJHKMsOGx2OQvjLIj/KX8vXbfKvPCEPo1zQGLeklp+V469OHQ4/WxJX4uWhOjhlq+aoICPstnPBm0vr9QRG6nkY2yFFN2ZEj8Ncxkvmt+NQVXWHUR8+q2OpjVleEiO4OV5xcYrmfV6G5F5/oA=
    IBM_ENTITLED_REGISTRY_USER: AgAvaY1+ZGSTL9sh9WOMkc4tmv5783D34/zlPCllxlyVvXCiosEE8+TnQ0Cs3amHRYYx6T5RrMZvns5F+KCHaIjsEyAzlDXzavFbEy3DavVv57BTnQFqfEMslsGKFBZKoxt+aIffktGtIPvSY0ScqQH/X0e2M5YhbLu34PpH9lomDT3fq3S6TJiwQZeLZdQ0uvgCLu6mSx6S2UZf7Ns1SUlnS8IyjIbNDZJZtMzSTCzLaXBV9MIDSmm3Af5n39LLySYo0F7VTs9wOZNOQmRatpWYvrFx4OkrzkhqnBJRv/wlPbQSJvCnxwRSDb8O5se8mWy17qbm1q+YgONpAwaXzX+PPcJV8ntm5alRPLa8RXsC+LK8dWvHopJMTJdPIiFUa562vYU5d/9XntKkUiLoq63LG3SoJy1BiWJMIGoTTEDalArvgowDi0nkJC5suJPpory+REicclpzfByopePKeAah7zUnmnOaQfuKvBSjtTZim3mx3AV3jsKmcNBes/FAa230Q9WDriT7aaq7kpjRE2Hzma244H3KO3p+Kn+5jPNo/HjnBZ88QxiwWmI1vuXWrtLrtGLPU00Fh7sCN57vRlxVzYnGJMca5YDPYvPk8FHh4uPJFr3i8t8aEXdmLPr19rPBDgX7i45awJdJhtWlxQ6NzWxLeCE+XeFYCaQzW/34je8wzc+DI3h48a7RSxhZPBOSDA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

