apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
  name: cnkt-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: TriggerBinding
      ref: cnkt-trigger-binding
    interceptors:
    - cel:
        filter: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master' && body.repository.full_name == 'client-engineering-gitops-h/lauren-demo'
    name: lauren-demo-dev
    template:
      ref: lauren-demo-dev
  # - bindings:
  #   - kind: TriggerBinding
  #     ref: cnkt-trigger-binding
  #   interceptors:
  #   - cel:
  #       filter: header.match('X-GitHub-Event', 'push') && body.ref == 'refs/heads/master' && body.repository.full_name == 'client-engineering-gitops-h/lauren-demo'
  #   name: Lauren-demo-dev
  #   template:
  #     ref: Lauren-demo-dev
