apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  labels:
    app: cnkt-event-listener
    app.kubernetes.io/instance: apps-lauren-demo-rest-ci-1
  name: cnkt-event-listener
  namespace: ci
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: cnkt-trigger-binding
      interceptors:
        - params:
            - name: "filter"
              value: "header.match('X-GitHub-Event', 'push') && body.ref =='refs/heads/lauren-demo-client-engineering-gitops-h' && body.repository.full_name == 'client-engineering-gitops-h/lauren-demo'"
          ref:
            name: "cel"
      name: lauren-demo-dev
      template:
        ref: lauren-demo-dev